#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x2790ccd3, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x480fae03, __VMLINUX_SYMBOL_STR(clk_unprepare) },
	{ 0xda63cdca, __VMLINUX_SYMBOL_STR(cdev_del) },
	{ 0xcb3a734a, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xe51fed5d, __VMLINUX_SYMBOL_STR(cdev_init) },
	{ 0xfa4356a, __VMLINUX_SYMBOL_STR(__pm_runtime_idle) },
	{ 0xf935a32c, __VMLINUX_SYMBOL_STR(of_property_read_string_helper) },
	{ 0xfbc74f64, __VMLINUX_SYMBOL_STR(__copy_from_user) },
	{ 0x7351840a, __VMLINUX_SYMBOL_STR(sps_register_bam_device) },
	{ 0x98cc564a, __VMLINUX_SYMBOL_STR(regulator_set_voltage) },
	{ 0xc2c7fa3a, __VMLINUX_SYMBOL_STR(clk_enable) },
	{ 0xea06bc7, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0xf22ec8b9, __VMLINUX_SYMBOL_STR(debugfs_create_dir) },
	{ 0x46e748ad, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0x67c2fa54, __VMLINUX_SYMBOL_STR(__copy_to_user) },
	{ 0xc996d097, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x8d96b647, __VMLINUX_SYMBOL_STR(dev_set_drvdata) },
	{ 0xee4f3181, __VMLINUX_SYMBOL_STR(wakeup_source_add) },
	{ 0xcf8cc5ee, __VMLINUX_SYMBOL_STR(msm_bus_scale_unregister_client) },
	{ 0x32e11075, __VMLINUX_SYMBOL_STR(devm_kzalloc) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x31472e84, __VMLINUX_SYMBOL_STR(sps_deregister_bam_device) },
	{ 0x1258d9d9, __VMLINUX_SYMBOL_STR(regulator_disable) },
	{ 0x23fee123, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0xad46dec2, __VMLINUX_SYMBOL_STR(of_count_phandle_with_args) },
	{ 0x1525f36d, __VMLINUX_SYMBOL_STR(__pm_stay_awake) },
	{ 0x8bde678e, __VMLINUX_SYMBOL_STR(sps_alloc_endpoint) },
	{ 0xb21d93eb, __VMLINUX_SYMBOL_STR(sps_device_reset) },
	{ 0x64021802, __VMLINUX_SYMBOL_STR(uncached_logk) },
	{ 0xa05fcf6b, __VMLINUX_SYMBOL_STR(sps_connect) },
	{ 0x3ae79c12, __VMLINUX_SYMBOL_STR(clk_disable) },
	{ 0x9dec3162, __VMLINUX_SYMBOL_STR(device_destroy) },
	{ 0xdac11bae, __VMLINUX_SYMBOL_STR(of_property_read_u32_array) },
	{ 0x2e1ca751, __VMLINUX_SYMBOL_STR(clk_put) },
	{ 0x78f062cb, __VMLINUX_SYMBOL_STR(msm_bus_scale_client_update_request) },
	{ 0x4c2ae700, __VMLINUX_SYMBOL_STR(strnstr) },
	{ 0x593a99b, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x93940e0c, __VMLINUX_SYMBOL_STR(sps_transfer_one) },
	{ 0x45f2c3d3, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0x7485e15e, __VMLINUX_SYMBOL_STR(unregister_chrdev_region) },
	{ 0x136d88ec, __VMLINUX_SYMBOL_STR(debugfs_create_file) },
	{ 0xb5aa7165, __VMLINUX_SYMBOL_STR(dma_pool_destroy) },
	{ 0xd36967ea, __VMLINUX_SYMBOL_STR(sps_get_iovec) },
	{ 0x7e58d205, __VMLINUX_SYMBOL_STR(debugfs_remove_recursive) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x9f79305e, __VMLINUX_SYMBOL_STR(simple_attr_read) },
	{ 0xfcdb4034, __VMLINUX_SYMBOL_STR(wakeup_source_prepare) },
	{ 0xcc3fcbca, __VMLINUX_SYMBOL_STR(sps_get_config) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x27a9dc4, __VMLINUX_SYMBOL_STR(debugfs_create_u32) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x94075b7e, __VMLINUX_SYMBOL_STR(msm_bus_cl_get_pdata) },
	{ 0x2c9045af, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x87d1cdd3, __VMLINUX_SYMBOL_STR(sps_disconnect) },
	{ 0x43632d7d, __VMLINUX_SYMBOL_STR(of_find_property) },
	{ 0x71930ed3, __VMLINUX_SYMBOL_STR(of_property_read_string) },
	{ 0xfaef0ed, __VMLINUX_SYMBOL_STR(__tasklet_schedule) },
	{ 0x9545af6d, __VMLINUX_SYMBOL_STR(tasklet_init) },
	{ 0xc1f5e7c8, __VMLINUX_SYMBOL_STR(device_create) },
	{ 0x8834396c, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0xf54c51a2, __VMLINUX_SYMBOL_STR(dma_pool_free) },
	{ 0x74365c38, __VMLINUX_SYMBOL_STR(simple_attr_release) },
	{ 0xd6b8e852, __VMLINUX_SYMBOL_STR(request_threaded_irq) },
	{ 0x77837920, __VMLINUX_SYMBOL_STR(platform_driver_register) },
	{ 0xf2fc7f6e, __VMLINUX_SYMBOL_STR(__pm_relax) },
	{ 0x25d20f2a, __VMLINUX_SYMBOL_STR(cdev_add) },
	{ 0xfe0d7bc8, __VMLINUX_SYMBOL_STR(clk_round_rate) },
	{ 0xaa0a0ec2, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x550cf274, __VMLINUX_SYMBOL_STR(devm_regulator_get) },
	{ 0xd4482f7b, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x644f2bdf, __VMLINUX_SYMBOL_STR(platform_get_irq_byname) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xc2165d85, __VMLINUX_SYMBOL_STR(__arm_iounmap) },
	{ 0xe5e68643, __VMLINUX_SYMBOL_STR(clk_prepare) },
	{ 0x6e8c3e8, __VMLINUX_SYMBOL_STR(__pm_runtime_set_status) },
	{ 0x2646f2e8, __VMLINUX_SYMBOL_STR(sps_free_endpoint) },
	{ 0x3757c9b, __VMLINUX_SYMBOL_STR(of_get_named_gpio_flags) },
	{ 0xee3496c3, __VMLINUX_SYMBOL_STR(dma_pool_alloc) },
	{ 0x6cfa9126, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9a8ba581, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x7b6dd897, __VMLINUX_SYMBOL_STR(clk_get) },
	{ 0xbc884c6c, __VMLINUX_SYMBOL_STR(clk_set_rate) },
	{ 0x1547645, __VMLINUX_SYMBOL_STR(platform_get_resource_byname) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x7ded90b3, __VMLINUX_SYMBOL_STR(msm_bus_scale_register_client) },
	{ 0x499cb58c, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0xd13c760f, __VMLINUX_SYMBOL_STR(gpio_tlmm_config) },
	{ 0x1021ea03, __VMLINUX_SYMBOL_STR(class_destroy) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xf425ca2d, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xfb961d14, __VMLINUX_SYMBOL_STR(__arm_ioremap) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0xa98ae857, __VMLINUX_SYMBOL_STR(sps_register_event) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x4264d9b, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0x81695a8d, __VMLINUX_SYMBOL_STR(dma_pool_create) },
	{ 0xc719f939, __VMLINUX_SYMBOL_STR(__class_create) },
	{ 0x8a669fd9, __VMLINUX_SYMBOL_STR(dev_get_drvdata) },
	{ 0x987735f1, __VMLINUX_SYMBOL_STR(simple_attr_open) },
	{ 0xed06b916, __VMLINUX_SYMBOL_STR(wakeup_source_drop) },
	{ 0xff5cda7c, __VMLINUX_SYMBOL_STR(wakeup_source_remove) },
	{ 0x29537c9e, __VMLINUX_SYMBOL_STR(alloc_chrdev_region) },
	{ 0x7457ed97, __VMLINUX_SYMBOL_STR(simple_attr_write) },
	{ 0xf20dabd8, __VMLINUX_SYMBOL_STR(free_irq) },
	{ 0xca16dbe7, __VMLINUX_SYMBOL_STR(regulator_enable) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

